version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: appdockerfile
    restart: always
    networks:
      gennet:
    environment:
      DB_HOST: mongodb://db:27017/posts
    volumes:
      - /Users/chris/Documents/Sparta/Docker/app:/usr/src/app
    ports:
      - "80:3000"
    container_name: app
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      gennet:
    container_name: db
    command: mongod --bind_ip_all

networks:
  gennet:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
